# Generated by Django 2.1 on 2018-08-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('title', models.TextField(verbose_name='标题')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='子标题')),
                ('url', models.URLField(verbose_name='链接地址')),
            ],
            options={
                'verbose_name': 'Rss地址',
                'verbose_name_plural': 'Rss地址',
                'ordering': ['id'],
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Feed2User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('owner_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss2user_feed', to='feed.Feed', verbose_name='Rss')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss2user_user', to='user.User', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户Rss',
                'verbose_name_plural': '用户Rss',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('title', models.TextField(default='', verbose_name='标题')),
                ('published', models.TextField(default='', verbose_name='发布时间')),
                ('author', models.CharField(default='', max_length=32, verbose_name='作者')),
                ('link', models.TextField(default='', verbose_name='链接')),
                ('summary', models.TextField(default='', verbose_name='描述')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('owner_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feed', to='feed.Feed', verbose_name='所属Rss')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
            bases=('base.basemodel',),
        ),
    ]
