# Generated by Django 2.1 on 2018-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='author',
            field=models.TextField(default='', verbose_name='作者'),
        ),
    ]
