# Generated by Django 2.1 on 2018-08-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='author',
        ),
    ]
