# Generated by Django 2.1 on 2018-08-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssUrls',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('title', models.TextField(verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接地址')),
            ],
            options={
                'verbose_name': 'Rss地址',
                'verbose_name_plural': 'Rss地址',
                'ordering': ['id'],
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('username', models.TextField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='用户名')),
                ('password', models.TextField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('nickname', models.TextField(default='', max_length=32, verbose_name='昵称')),
                ('phone', models.TextField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('openid', models.TextField(default='', verbose_name='微信openid')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
            bases=('base.basemodel',),
        ),
        migrations.AddField(
            model_name='rssurls',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='所属用户'),
        ),
    ]
